# Generated by Django 4.2.16 on 2024-10-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoRaTimeSyncServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecollection',
            name='time_expected',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='timecollection',
            name='time_received',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='timesyncinit',
            name='first_uplink_expected',
            field=models.BigIntegerField(),
        ),
    ]
