# Generated by Django 4.2.16 on 2024-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoRaTimeSyncServerApp', '0002_alter_timecollection_time_expected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecollection',
            name='device_time',
            field=models.BigIntegerField(),
        ),
    ]
