# Generated by Django 4.2.16 on 2024-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoRaTimeSyncServerApp', '0003_alter_timecollection_device_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesyncmodels',
            name='new_period_ms',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timesyncmodels',
            name='new_period_ns',
            field=models.BigIntegerField(null=True),
        ),
    ]
