# Generated by Django 4.2.16 on 2025-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoRaTimeSyncServerApp', '0004_timesyncmodels_new_period_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesyncmodels',
            name='last_collection_time_received',
            field=models.BigIntegerField(null=True),
        ),
    ]
