# Generated by Django 4.2.16 on 2025-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoRaTimeSyncServerApp', '0005_timesyncmodels_last_collection_time_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesyncmodels',
            name='offset',
            field=models.BigIntegerField(null=True),
        ),
    ]
