version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/loratimesync

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loratimesync
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HOST=10.0.190.13
      - CHIRPSTACK_API_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjFmZTk1ZmQwLTExMmEtNGIwMi1hZTAxLTYwOWFiZGY2ODZhYiIsInR5cCI6ImtleSJ9.ssQzuAUWvbHJTA4nqZXqUNvz7rPKV-NW3AuIFpOhiaw
    ports:
      - "5432:5432"

volumes:
  postgres_data:
